language: python
os: linux
dist: xenial
install:
  - pip install -r requirements.txt
notifications:
  email:
    recipients:
      - ricardo.montanana@alu.uclm.es
    on_success: never # default: change
    on_failure: always # default: always
# command to run tests
script: python -m unittest tests.Stree_test tests.Snode_test