coverage:
  status:
    project:
      default:
        target: 100%
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: yes
  require_head: yes
  branches: null
